[SQUASH]build: Add rising system props
Fixes:
error: ADDITIONAL_BUILD_PROPERTIES is obsolete.  Please use ADDITIONAL_SYSTEM_PROPERTIES.
Change-Id: I7eb3c47d9fd705aa8f8d39e10563e47ffbf2d560
build: set build fingerprint for all devices

* there's no per device way to add props to /system/build.prop
* adding it here is the only way so far

Change-Id: Iafc286d9e479677540a4ec617db76715c018ae8e
build: Clean up makefile inclusions

* Include MTK/QCOM rules directly from the build/core/config.mk hook.
* Place main.mk hook and main_version.mk into build/core with the rest
  of the make system hooks.

Change-Id: Iad2f808f3e3eefbd2be2ca5facb907ff31babbb7
lineage: Isolate LineageOS versions properties for build.prop

 * Our properties were supposed to go to /system/etc/prop.default
    after the following commit:
    "lineage: Move to Google's method of defining system default props"
    Change-Id: I6cb0e28a7599b010b389cc541015a37010a00f4b

 * However if BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED is not true,
    only /default.prop will retain the properties contents of
    ADDITIONAL_DEFAULT_PROPERTIES and PRODUCT_SYSTEM_DEFAULT_PROPERTIES,
    and none of our versioning identification was held in the system

 * Enabling BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED globally would
    break all properties on devices that handle partitions usually
    at the device level rather than the kernel due to mounting races

 * Create a new main_version.mk file to isolate LineageOS properties
    that define the system's versions identifications, and use the
    ADDITIONAL_BUILD_PROPERTIES internal build variable to include
    from build/make through a common vendor main.mk entrypoint

Change-Id: I0060141c097b3d14c3710eee1e0caf7110634967
Signed-off-by: Adrian DC <radian.dc@gmail.com>
Signed-off-by: Alvin Francis <nivlafx@gmail.com>