[SQUASH]Import soong bits from LOS
Hookup GRALLOC_HANDLE_HAS_UBWCP_FORMAT

The gralloc struct has been conditionally adjusted not to
break blobs that use the old struct.

Change-Id: I4dd1d1890ad08364d5315386ab830ce9e0edd041
vendor/lineage: Hookup TARGET_CAMERA_OVERRIDE_FORMAT_FROM_RESERVED

Change-Id: I67b87e98b65300df9a63ddd6d316ae4dd33ab427
Hookup GRALLOC_HANDLE_HAS_CUSTOM_CONTENT_MD_RESERVED_SIZE

The gralloc struct has been conditionally adjusted not to
break blobs that use the old struct.

So far only GRALLOC_HANDLE_HAS_RESERVED_SIZE was hooked up
for Google Pixels, but it's now time to hook up the remaining flag.

Change-Id: I175bd328bd9733b9487e349f7a8486f15ef0a450
soong: Add `aapt_version_code` default

This appends `--version_code=$(date -u +%Y%m%d)` to aapt flags, which is
useful for flushing some caches upon system updates.

Change-Id: I6575b878f09c1c3138e12abc34d39405f51245e7
soong: Add TARGET_HEALTH_CHARGING_CONTROL related configs

To specify the charging control allowed modes:
TARGET_HEALTH_CHARGING_CONTROL_SUPPORTS_{BYPASS,DEADLINE,TOGGLE},

To specify the charging control paths:
TARGET_HEALTH_CHARGING_CONTROL_{CHARGING_PATH,DEADLINE_PATH},

To specify data written to TARGET_HEALTH_CHARGING_CONTROL_CHARGING_PATH:
TARGET_HEALTH_CHARGING_CONTROL_CHARGING_{ENABLE,DISABLE}

Change-Id: I88831c84966f82648c8ca60de5abb34416140f6c
soong: Bring bootloader_message_offset back

This is squashed revert of:

    Revert "config: Remove BOOTLOADER_MESSAGE_OFFSET"

    This reverts commit a8bbd0e4aa41915818774984e04c977afe234498.

    Change-Id: I66df34e901e87e543102377469a150a9bf03e5b8

    Revert "Revert "soong: Export bootloader_message_offset to dependencies""

    This reverts commit d0b4f9894add43e5caa8720575391e781cab2cf2.

    Reason for revert: Bringing this back, LGE 8996 lives.

    Change-Id: Iae68fee53ba647d8c64c54388e7296232adf4db8

Change-Id: I358d8e19f2d4da590c9579c1473b5f1964bb71aa
config: Remove TARGET_CAMERA_BOOTTIME_TIMESTAMP

This is no longer needed in T

Change-Id: Id14c88a548c14a8c26858a13f262f355ba72745e
fixup! Hookup GRALLOC_HANDLE_HAS_RESERVED_SIZE

Change-Id: Id12058a238c241acb138e3e419bb0bab8280e51b
Hookup GRALLOC_HANDLE_HAS_RESERVED_SIZE

* Needed for camera on redbull 13

Change-Id: Ibc1d941f8a6e5e61e3a56cb0065e387022fa3441
config: Remove BOOTLOADER_MESSAGE_OFFSET

This hasn't been ported after lineage-18.1

Change-Id: Ie3d798a009a4e0042b767839b39dd6f68695ef2a
config: Remove TARGET_PROCESS_SDK_VERSION_OVERRIDE

This hasn't been ported after lineage-18.1

Change-Id: I3024e503e97075d5bfffc41b60da83a445a4e580
config: Remove TARGET_DISABLE_POSTRENDER_CLEANUP

This hasn't been ported after lineage-18.1

Change-Id: Ib1bca251c6de7529c58ea2fb9b439e37b55be6c5
config: Remove TARGET_NEEDS_NETD_DIRECT_CONNECT_RULE

This hasn't been ported after lineage-18.1

Change-Id: I2946fdb08c09a3bfd238d65103869dc89ca2b558
config: Remove TARGET_IGNORES_FTP_PPTP_CONNTRACK_FAILURE

This hasn't been ported after lineage-17.1

Change-Id: I2aff9bb7bc17fa1444a904d47248d885268bf29b
config: Remove TARGET_HAS_MEMFD_BACKPORT

Change-Id: I17444007429f826bf3d7504cba760204c476e664
config: Remove TARGET_SPECIFIC_CAMERA_PARAMETER_LIBRARY

This hasn't been ported after lineage-18.1

Change-Id: Ib3ae63ee549b774349268a42923e462a3ef975a0
config: Remove TARGET_HAS_LEGACY_CAMERA_HAL1

Change-Id: I6f4cbe41f6df3ceb6b4058d5b6e77c02e1899809
config: Remove TARGET_USES_QCOM_BSP_LEGACY

Change-Id: I93f111285c46e1a1f811b9d8555de96474d60386
config: Remove QCOM HW FDE setup

Change-Id: Ia88a5331e5f3b69a2eea95aa13338f4282779856
soong: Add TARGET_USES_EGL_DISPLAY_ARRAY conditional

This soong variable is used to conditionally revert a commit [1]
which causes random camera crashes on tama devices

[1] https://github.com/LineageOS/android_frameworks_native/commit/a9550f3fe9097e0934e9b44c5aac6b914fb46aec

Change-Id: I749c7029f8f2b6d6d95b066aed4929c33e3c75e7
soong: Drop TARGET_USES_QTI_CAMERA_DEVICE

* qcom-camera topic hasn't been ported to 19.1

Change-Id: Ifb053d215527d602109bbb451d96ec80cf028548
soong: Add TARGET_TRUST_USB_CONTROL_{PATH,ENABLE,DISABLE}

Change-Id: Ib245114588fd14c83069e4365f9ca3e9e9536ba9
soong: Rename fod to udfps

 * now flag is changed to TARGET_SURFACEFLINGER_UDFPS_LIB from TARGET_SURFACEFLINGER_FOD_LIB

Change-Id: I499b31d00a053b865ceaa3b34a9762f980bbf14e
Revert "soong: Export bootloader_message_offset to dependencies"

* Fix build, revert when/if this is needed again.

This reverts commit 1b4ecdcb1cbf873cc70ada41faa6693511601720.

Change-Id: I14ec026d8be7297319564340b84ceb164dccfdd5
soong: Add TARGET_CAMERA_BOOTTIME_TIMESTAMP conditional

Change-Id: Ic48acda208fc9990fc5c9159ad06518d48f21477
Revert "soong: Add TARGET_QTI_USB_SUPPORTS_{AUDIO,DEBUG}_ACCESSORY flags"

This reverts commit ba8e075ed4d7cc079ab2e8a297da28df5ef3b8e7.
It is no longer necessary.

Change-Id: I5d9656ffb686e939f006d5fb1effaba835f93ed2
generated_kernel_headers: Also add usr/include/audio to include path

Needed for QGKI 5.4.

Change-Id: I44c77167828fdc3577cfd1eb548c8ceb7c418cbb
soong: Add TARGET_QTI_USB_SUPPORTS_{AUDIO,DEBUG}_ACCESSORY flags

Change-Id: I18a93fa12bf3d911919a80996d41d52714ee42bf
soong: Add TARGET_LEGACY_HW_DISK_ENCRYPTION conditional

Change-Id: I2c67fe632d415353273839493a86cdd75bd93b23
lineage: Commonize display_intf_headers for QSSI supported platforms

Change-Id: I7224c10295c4123222d81b92f7829502e3cc2d61
soong: add TARGET_HAS_MEMFD_BACKPORT conditional

Change-Id: I71b3a86c96bfe53e93e99c071bc8f3a8c56c77b7
soong: Add flag for disabling postrender cleanup

Some legacy devices experiences bad lag unless this is disabled.

Disable it with:
TARGET_DISABLE_POSTRENDER_CLEANUP := true

Change-Id: I2b40dc4cbcab06fb293d1f407321af2fae846a51
fixup! soong: Add lineage soong config variables

error: system/netd/server/Android.bp:162:1: module "netd" variant "android_arm64_armv8-a_cfi": cppflags: Flag DIGNORES_FTP_PPTP_CONNTRACK_FAILURE must start with -

Signed-off-by: Aayush Gupta <aayushgupta219@gmail.com>
Change-Id: I24b89f13425cf586e6ff50d83e71fb1a052bf4ed
soong: Export bootloader_message_offset to dependencies

Change-Id: I5b81d4a58406b1b521297a217dc33086e70259d0
soong: Add lineage soong config variables

Ref: https://android.googlesource.com/platform/build/soong/+/refs/tags/android-11.0.0_r4#soong-config-variables

Change-Id: Icaf35b65b63d4245c92e39ce628bb8d6ffd0d4bb
Revert lineage soong product variables changes

 * This reverts commits 7ef0e170 and 4ed4605 and removes relevant flags
   to prepare for using Soong config variables as per Google's docs

Change-Id: Ib6ae5a8a922104d37f8d0e08242b428eb129785c
soong: Run bpfix

Change-Id: Id528c99180d34129862c67ef92a00a5ef0fdf61e
Export CAF msm-4.14 audio headers

Change-Id: Idc7def38ad90abf4a62e30b3cec97bcb76696a6d
Export techpack/audio uapi headers of msm 4.14 kernel

 * With the techpack integration implementation of Google's msm-4.14
   kernel https://bit.ly/2WqiMFx (CAF didn't port this to their kernel
   thus suppose Google's port is the standard one), these headers are
   installed to include/audio/include/uapi.
 * This fixes building audio HAL with 4.14 kernel

Change-Id: I8283699470a7bcb31c771c9aa770a825b4e82519
lineage: Mark generated_kernel_includes as recovery_available

Change-Id: Id4eed981e601244330a8ced1d5433254d808b3fd
kernel: Use absolute path for kernel O= argument

The kernel make command is executed in the build root. Without absolute
out paths, kernel out start with "out/" meaning it would be created in
the kernel source. Add BUILD_ROOT to the argument to ensure it's always
made in the actual out/ dir.

Change-Id: I425134a893d4d5c9f31efccaf75e153b5462b76c
kernel: Use prebuilt binaries

perl, lz4c, and a bunch of other binaries are not allowed anymore.
So we need to provide our own.

Change-Id: Idbc88b76247b3dda7c5d52e5eed2d548c33f6f2d
kernel: Use full path to the make command

make is now a dissallowed command so just run the full command

Change-Id: I9390dc5a8bcd17f316354b88bdbc65ac8663b369
Revert "vendor/lineage: Add support for java source overlays"

This reverts commit af9697550607a5e2d206384b322fe65fe285e85c.

Change-Id: I837a5a8e8523e9e9959abe83dabcc333e87eac17
lineage: Add techpack/audio to include path also

Change-Id: Ib5af4c77f3342c01325e32222401d7584bac337a
lineage: Consider techpack/audio when generating kernel headers

 * New fancy kernels have techpack modules and we need to
   account for headers of those modules.

Change-Id: I4da9606d5933209287dd5e881f06ee1e39443f70
lineage: Dynamically generate kernel headers using lineage generator

Add a soong vendor plugin for kernel config variables so we can use
these in go.

Change-Id: Id31f2be8fcc5aba2d965dbe815edaaf1d28279c6
vendor/lineage: Add soong generator module type

*) Similar to genrule but can be used to generate content
   when the output directory and file structure are not
   known ahead of time.

*) An example use case is to build kernel headers.

Change-Id: I10deb7ba8825393b0b5fdbf2d96b12ad37257e12
vendor/lineage: Add support for java source overlays

*) Set JAVA_SOURCE_OVERLAYS in a device makefile as follows:
   # Java sourcefile overlays (for Android.bp built modules only)
   # Format is a whitespace separated set of rules, each of which
   # structured as follows:
   # modulename|overlay directory|glob pattern within overlay dir
   JAVA_SOURCE_OVERLAYS := \
           org.lineageos.hardware|$(LOCAL_PATH)/lineagehw|**/*.java

*) As of this commit, java sources overlays are only allowed for
   module org.lineageos.hardware.

Change-Id: I6be1c12567081357f5231a84df98ac002c0563b4
lineage: add soong bits for boardflags

Change-Id: If01db1eb6b1432a6c4d26d5c9701895ab4dc3ff5
Signed-off-by: Alvin Francis <nivlafx@gmail.com>

# Conflicts:
#	config/BoardConfigQcom.mk